# Generated by Django 4.1.1 on 2022-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('age', models.PositiveIntegerField()),
                ('phone_no', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('addressDetails', models.CharField(max_length=20)),
                ('home_no', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
